### ISSUE TITLE
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'

### ISSUE THREAD

**Issue by rjblake** [colin-guyon/py-bluetooth-utils#6]
Any idea how to fix this? I can't seem to determine what is missing to get it to work.

pi@raspi:~/py-bluetooth-utils $ python3.9 example_ble_scan.py
Traceback (most recent call last):
  File "/home/pi/py-bluetooth-utils/example_ble_scan.py", line 13, in <module>
    toggle_device(dev_id, True)
  File "/home/pi/py-bluetooth-utils/bluetooth_utils.py", line 88, in toggle_device
    hci_sock = socket.socket(socket.AF_BLUETOOTH,
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'

**Comment by ZHCSOFT** [comment]
Use system-provided python. Do not use python installed via conda
